version: "3.7"

services: 

    flask:
        build: ./flask
        container_name: flask
        restart: always
        environment: 
            - APP_NAME=VerifyLeadsAPI
            - DB_USERNAME=example
            - FLASK_ENV=development
            - DATABASE_URL=postgres://postgres:secret@localhost:54320/verifyleads
            - JWT_SECRET_KEY=Arnidara123#4
            - ADMIN_USERNAME=adminaryan9711
            - ADMIN_PASSWORD=Arnidara123#
            - ACCESS_KEY='AKIAQPJ4EMLJPPI7A56F'
            - SECRET_KEY='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'
            - BUCKET='verifyleads'
        expose: 
            - 8080
    
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports: 
            - "80:80"

    db:
        image: "postgres:11"
        container_name: "postgres"
        ports:
        - "54320:5432"
        volumes:
        - my_dbdata:/var/lib/postgresql/data
volumes:
    my_dbdata: