"""empty message

Revision ID: 1177fde75a92
Revises: a620a2238e5a
Create Date: 2020-06-02 19:39:29.058250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1177fde75a92'
down_revision = 'a620a2238e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company', sa.String(length=128), nullable=True, default = None))
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True, default = "test"))
    op.execute("UPDATE users SET email = 0")
    op.alter_column('users', 'email', nullable=False)
    op.add_column('users', sa.Column('imgUrl', sa.String(length=128), nullable=True, default = None))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('users', 'imgUrl')
    op.drop_column('users', 'email')
    op.drop_column('users', 'company')
    # ### end Alembic commands ###
