"""empty message

Revision ID: 58ca0404b263
Revises: 3fd30563c303
Create Date: 2020-05-01 01:20:06.169813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ca0404b263'
down_revision = '3fd30563c303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailleads', sa.Column('username', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emailleads', 'username')
    # ### end Alembic commands ###
