"""empty message

Revision ID: 7998869c21f7
Revises: 1177fde75a92
Create Date: 2020-06-02 19:58:23.039895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7998869c21f7'
down_revision = '1177fde75a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('f_name', sa.String(length=128), nullable=True, default = None))
    op.add_column('users', sa.Column('l_name', sa.String(length=128), nullable=True, default = None))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('users', 'l_name')
    op.drop_column('users', 'f_name')
    # ### end Alembic commands ###
