"""empty message

Revision ID: 8d3b58fed6cb
Revises: ae8b32e1f2ea
Create Date: 2020-04-30 22:16:38.369274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3b58fed6cb'
down_revision = 'ae8b32e1f2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=128), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
