"""empty message

Revision ID: a1b3dfb71955
Revises: dc9f83b34f8a
Create Date: 2020-06-02 18:37:24.485648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b3dfb71955'
down_revision = 'dc9f83b34f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_date', sa.DateTime(), nullable=True, default = None))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_date')
    # ### end Alembic commands ###
