"""empty message

Revision ID: c2c84ae8303e
Revises: 8d3b58fed6cb
Create Date: 2020-04-30 22:53:27.482425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c84ae8303e'
down_revision = '8d3b58fed6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailleads', sa.Column('message', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emailleads', 'message')
    # ### end Alembic commands ###
