"""empty message

Revision ID: dc9f83b34f8a
Revises: 51b9acbac764
Create Date: 2020-05-08 19:16:48.318202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9f83b34f8a'
down_revision = '51b9acbac764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailleads', sa.Column('f_name', sa.String(length=128), nullable=True, default = None))
    op.add_column('emailleads', sa.Column('l_name', sa.String(length=128), nullable=True, default = None))
    op.add_column('emailleads', sa.Column('m_name', sa.String(length=128), nullable=True, default = None))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emailleads', 'm_name')
    op.drop_column('emailleads', 'l_name')
    op.drop_column('emailleads', 'f_name')
    # ### end Alembic commands ###
